//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proteinocn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunTable()
        {
            this.sepetTable = new HashSet<sepetTable>();
        }
    
        public short urun_id { get; set; }
        public string urun_ad { get; set; }
        public string urun_aroma { get; set; }
        public string urun_boyut { get; set; }
        public int urun_fiyat { get; set; }
        public string urun_aciklama1 { get; set; }
        public string urun_aciklama2 { get; set; }
        public string urun_foto1 { get; set; }
        public string urun_foto2 { get; set; }
        public string urun_kategori { get; set; }
        public string urun_aroma2 { get; set; }
        public string urun_aroma3 { get; set; }
        public string urun_aroma4 { get; set; }
        public string urun_aroma5 { get; set; }
        public string urun_boyut2 { get; set; }
        public string urun_boyut3 { get; set; }
        public string urun_ozellikler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepetTable> sepetTable { get; set; }
    }
}
