//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proteinocn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeTable()
        {
            this.sepetTable = new HashSet<sepetTable>();
        }
    
        public short uye_id { get; set; }
        public string uye_ad { get; set; }
        public string uye_sifre { get; set; }
        public string uye_eposta { get; set; }
        public string uye_adres { get; set; }
        public string uye_telno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepetTable> sepetTable { get; set; }
    }
}
